name: Release Packages
on:
  pull_request:
    types: [closed]
    branches: [V5]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'changeset-pr')
    name: Release Packages
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name:
      - uses: ./.github/actions/setup

      - name: Publish packages to NPM
        # Remove dry when ready
        run: npm run publish:dry
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        run: |
          PACKAGES=$(npx changeset status --output=json | jq -r '.releases[].name')
          CHANGES=$(npx changeset status --output=json | jq -r '.releases[].changesets[]')
          echo "Releasing packages: $PACKAGES"
          echo "Changesets: $CHANGES"
          VERSION=$(node -pe "require('./packages/core/package.json').version")
          gh release create "v$VERSION" --title "Release v$VERSION" --notes "Packages: $PACKAGES"
        env:
          GITHUB_TOKEN: ${{ secrets.CHANGESETS_ACTION_TOKEN }}
